#ifndef __CRIRegistryCAPListDlg__
#define __CRIRegistryCAPListDlg__

/**
@file
Subclass of CAPListDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "db/dbSingleton.h"
#include "db/dbClass.h"
#include "MyFunctions.h"
#include "UsersManager.h"
#include "CRIRegistryCAPDlg.h"

/** Implementing CAPListDlg */
class CRIRegistryCAPListDlg : public CAPListDlg
{
protected:
	// Handlers for CAPListDlg events.
	void OnAdd( wxCommandEvent& event );
	void OnModify( wxCommandEvent& event );
	void OnDel( wxCommandEvent& event );
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );

public:
	/** Constructor */
	CRIRegistryCAPListDlg( wxWindow* parent );
    ~CRIRegistryCAPListDlg();

    std::vector<dbClass>::iterator FieldSelect() {return m_FieldSelect; }
	
private:
	std::vector<dbClass>	m_Fields;
    std::vector<dbClass>::iterator m_FieldSelect;
	std::vector<dbClass>::iterator GetFieldSelected();
    long GetItemSelected();
    void UpdateList();
};

#endif // __CRIRegistryCAPListDlg__
