#ifndef __CRIRegistryAddFieldsDlg__
#define __CRIRegistryAddFieldsDlg__

/**
@file
Subclass of AddFieldsDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "db/dbSingleton.h"
#include "db/dbClass.h"
#include "MyFunctions.h"
#include "UsersManager.h"

/** Implementing AddFieldsDlg */
class CRIRegistryAddFieldsDlg : public AddFieldsDlg
{
protected:
	// Handlers for AddFieldsDlg events.
	void OnAdd( wxCommandEvent& event );
	void OnModify( wxCommandEvent& event );
	void OnDel( wxCommandEvent& event );
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );

public:
	/** Constructor */
	CRIRegistryAddFieldsDlg( wxWindow* parent, const wxString& table, const wxString& id, const wxString& field, const wxString& condition = wxEmptyString );
    ~CRIRegistryAddFieldsDlg();
    dbClass* FieldToAdd(){ return &m_ItemToAdd; }

private:
	wxString				m_szTable;
	wxString				m_szIdFieldName;
	wxString				m_szFieldName;
    dbClass                 m_ItemToAdd;
	std::vector<dbClass>	m_Fields;
	std::vector<dbClass>::iterator GetFieldSelected();
};

#endif // __CRIRegistryAddFieldsDlg__
