#ifndef __CRIRegistryCheckListDlg__
#define __CRIRegistryCheckListDlg__

/**
@file
Subclass of CheckListDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryCheckListPagesGUIs.h"

//// end generated include

/** Implementing CheckListDlg */
class CRIRegistryCheckListDlg : public CheckListDlg
{
	protected:
		// Handlers for CheckListDlg events.
		void OnOk( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		/** Constructor */
		CRIRegistryCheckListDlg( wxWindow* parent );
	//// end generated class members


};

#endif // __CRIRegistryCheckListDlg__
