#ifndef __CRIRegistryCheckListTimeIntervalDlg__
#define __CRIRegistryCheckListTimeIntervalDlg__

/**
@file
Subclass of CheckListTimeIntervalDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryCheckListPagesGUIs.h"
#include "CRIRegistryCheckListTimeDlg.h"

/** Implementing CheckListTimeIntervalDlg */
class CRIRegistryCheckListTimeIntervalDlg : public CheckListTimeIntervalDlg
{
protected:
		// Handlers for CheckListTimeIntervalDlg events.
		void OnAdd( wxCommandEvent& event );
		void OnEdit( wxCommandEvent& event );
		void OnDel( wxCommandEvent& event );
		void OnOk( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );

public:
		/** Constructor */
		CRIRegistryCheckListTimeIntervalDlg( wxWindow* parent );
};

#endif // __CRIRegistryCheckListTimeIntervalDlg__
