#ifndef __CRIRegistryShiftDlg__
#define __CRIRegistryShiftDlg__

/**
@file
Subclass of ShiftDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "dbClass/CShift.h"
#include "UsersManager.h"

const CShift DummyShift;

/** Implementing ShiftDlg */
class CRIRegistryShiftDlg : public ShiftDlg
{
protected:
	// Handlers for ShiftDlg events.
	void OnClose( wxCloseEvent& event );
    void OnChoice( wxCommandEvent& event );
	void OnWrite( wxKeyEvent& event );
	void OnExitCtrl( wxFocusEvent& event );
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	
public:
    /** Constructor */
    CRIRegistryShiftDlg( wxWindow* parent, const CShift& shift = DummyShift, eMode mode = ADD );

	const CShift& GetShift() { return m_Shift; }
    void SetShift( const CShift& s ) { m_Shift = s; }

private:
    CShift  m_Shift;
	eMode	m_Mode;

    void UpdateCtrl();
    bool UpdateData();
};

#endif // __CRIRegistryShiftDlg__
