#ifndef __CRIRegistryComunicationDlg__
#define __CRIRegistryComunicationDlg__

/**
@file
Subclass of ComunicationDlg, which is generated by wxFormBuilder.
*/
#include "CSmtp/CSmtp.h"

#include "CRIRegistryGUIs.h"
#include "dbClass/CComunication.h"
#include "UsersManager.h"
#include <wx/busyinfo.h>

const CComunication DummyComunication;

/** Implementing ComunicationDlg */
class CRIRegistryComunicationDlg : public ComunicationDlg
{
protected:
    // Handlers for ComunicationDlg events.
    void OnClose( wxCloseEvent& event );
    void OnExitCtrl( wxFocusEvent& event );
    void OnOk( wxCommandEvent& event );
    void OnCancel( wxCommandEvent& event );

public:
	/** Constructor */
	CRIRegistryComunicationDlg( wxWindow* parent, const CComunication& c = DummyComunication, eMode mode = ADD );
	const CComunication& GetComunication() { return m_Comunication; }
    void SetComunication( const CComunication& c ) { m_Comunication = c; }

private:
    CComunication           m_Comunication;
	eMode	                m_Mode;
    std::vector<dbClass>    m_MailingList;

    void UpdateCtrl();
    bool UpdateData();
    bool NeedToSendEmail();
    bool SendMail();
    wxArrayString GetMailAddress();
};

#endif // __CRIRegistryComunicationDlg__
