#ifndef __CRIRegistryCheckListEditDlg__
#define __CRIRegistryCheckListEditDlg__

/**
@file
Subclass of CheckListEditDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryCheckListPagesGUIs.h"
#include "CRIRegistryCheckListAddItemDlg.h"
#include "CRIRegistryOptions.h"

/** Implementing CheckListEditDlg */
class CRIRegistryCheckListEditDlg : public CheckListEditDlg
{
protected:
    // Handlers for CheckListEditDlg events.
    void OnChoice( wxCommandEvent& event );
    void OnItemActivate( wxTreeEvent& event );
    void OnAdd( wxCommandEvent& event );
    void OnEdit( wxCommandEvent& event );
    void OnDel( wxCommandEvent& event );
    void OnEditHours( wxCommandEvent& event );
    void OnOk( wxCommandEvent& event );
    void OnCancel( wxCommandEvent& event );

public:
    /** Constructor */
    CRIRegistryCheckListEditDlg( wxWindow* parent, const wxString& type = _("CENTRALINO"));

private:
    wxString m_Type;
    void UpdateItemsList();
    void EditItem( const wxTreeItemId& item );
};

#endif // __CRIRegistryCheckListEditDlg__
