#ifndef __CRIRegistryCheckListTimeDlg__
#define __CRIRegistryCheckListTimeDlg__

/**
@file
Subclass of CheckListTimeDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryCheckListPagesGUIs.h"

//// end generated include

/** Implementing CheckListTimeDlg */
class CRIRegistryCheckListTimeDlg : public CheckListTimeDlg
{
	protected:
		// Handlers for CheckListTimeDlg events.
		void OnExitCtrl( wxFocusEvent& event );
		void OnOk( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		/** Constructor */
		CRIRegistryCheckListTimeDlg( wxWindow* parent );
	//// end generated class members


};

#endif // __CRIRegistryCheckListTimeDlg__
