#ifndef __CRIRegistryAddCrewDlg__
#define __CRIRegistryAddCrewDlg__

/**
@file
Subclass of AddCrewDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "CRIRegistryCrewDlg.h"
#include "CRIRegistryOptions.h"
#include "dbClass/CShift.h"

/** Implementing AddCrewDlg */
class CRIRegistryAddCrewDlg : public AddCrewDlg
{
protected:
	// Handlers for AddCrewDlg events.
	void OnExitCtrl( wxFocusEvent& event );
	void OnChoice( wxCommandEvent& event );
	void OnAddCrew( wxCommandEvent& event );
	void OnModifyCrew( wxCommandEvent& event );
	void OnDelCrew( wxCommandEvent& event );
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );

public:
	/** Constructor */
	CRIRegistryAddCrewDlg( wxWindow* parent );
    const std::vector<CShift>& GetCrew() { return m_vCrew; }
    void SetCrew( std::vector<CShift> crew );

private:
    std::vector<CShift> m_vCrew;
    void UpdateCrewsListCtrl();
    long GetCrewItemSelected();
    std::vector<CShift>::iterator GetCrewSelected();
};

#endif // __CRIRegistryAddCrewDlg__
