#ifndef __CRIRegistryCheckListDlg__
#define __CRIRegistryCheckListDlg__

/**
@file
Subclass of CheckListDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryCheckListPagesGUIs.h"
#include "UsersManager.h"
#include "CRIRegistryOptions.h"
#include <wx/checkbox.h>
#include <wx/statbox.h>
#include <wx/sizer.h>
#include <vector>

// ============================================================================
//
// ============================================================================
class CItem : public wxBoxSizer
{
public:
    CItem( wxWindow* parent, int id, const wxString& name);
    void Update();
    void Set( bool checked, const wxString& note );
    bool IsChanged();
    bool IsChecked();

private:
    int             m_Id;
    wxCheckBox*     m_Name;
    wxTextCtrl*     m_txtNote;
    bool            m_Checked;
    wxString        m_Note;
};

// ============================================================================
//
// ============================================================================
class CPosition : public wxStaticBoxSizer
{
public:
    CPosition( wxWindow* parent, const wxString& name );
    void AddItem( CItem* item );
    void UpdateItems();
    bool IsChecked();

private:
    std::vector<CItem*>  m_Items;
};

// ============================================================================
// Implementing CheckListDlg
// ============================================================================
class CRIRegistryCheckListDlg : public CheckListDlg
{
protected:
    // Handlers for CheckListDlg events.
    void OnOk( wxCommandEvent& event );
    void OnCancel( wxCommandEvent& event );

public:
    /** Constructor */
    CRIRegistryCheckListDlg( wxWindow* parent, const wxString& type );
    
private:
    std::vector<CPosition*>  m_Positions;
};

#endif // __CRIRegistryCheckListDlg__
