#ifndef __CRIRegistryCheckListTimeIntervalDlg__
#define __CRIRegistryCheckListTimeIntervalDlg__

/**
@file
Subclass of CheckListTimeIntervalDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryCheckListPagesGUIs.h"
#include "CRIRegistryCheckListTimeDlg.h"
#include "CRIRegistryOptions.h"
#include <vector>


/** Implementing CheckListTimeIntervalDlg */
class CRIRegistryCheckListTimeIntervalDlg : public CheckListTimeIntervalDlg
{
protected:
    // Handlers for CheckListTimeIntervalDlg events.
    void OnAdd( wxCommandEvent& event );
    void OnEdit( wxCommandEvent& event );
    void OnDel( wxCommandEvent& event );
    void OnOk( wxCommandEvent& event );
    void OnCancel( wxCommandEvent& event );

public:
    /** Constructor */
    CRIRegistryCheckListTimeIntervalDlg( wxWindow* parent, const wxString& gruppo );

private:
    void UpdateList();

    wxString m_Gruppo;
    std::vector<dbRow> m_Items;
};

#endif // __CRIRegistryCheckListTimeIntervalDlg__
