#ifndef __CRIRegistrySearchDlg__
#define __CRIRegistrySearchDlg__

/**
@file
Subclass of SearchDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "CRIRegistryConstant.h"
#include "MyFunctions.h"

/** Implementing SearchDlg */
class CRIRegistrySearchDlg : public SearchDlg
{
protected:
	// Handlers for SearchDlg events.
	void OnOk( wxCommandEvent& event );
	void OnExitCtrl( wxFocusEvent& event );
	void OnCancel( wxCommandEvent& event );
	
public:
	/** Constructor */
	CRIRegistrySearchDlg( wxWindow* parent );
    int GetField() { return m_iField; }

    wxString GetValue() { return m_szValue; }
    wxString GetDateStart() { return m_szDateStart; }
    wxString GetDateEnd() { return m_szDateEnd; }

private:
	int			m_iField;
    wxString    m_szValue;
    wxString    m_szDateStart;
    wxString    m_szDateEnd;
};

#endif // __CRIRegistrySearchDlg__
