#ifndef __CRIRegistryCrewDlg__
#define __CRIRegistryCrewDlg__

/**
@file
Subclass of CrewDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "dbClass/CServiceCrew.h"

const CServiceCrew DummyCrew;

/** Implementing CrewDlg */
class CRIRegistryCrewDlg : public CrewDlg
{
protected:
	// Handlers for CrewDlg events.
	void OnWrite( wxKeyEvent& event );
	void OnExitCtrl( wxFocusEvent& event );
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );

public:
	/** Constructor */
	CRIRegistryCrewDlg( wxWindow* parent, const CServiceCrew& crew = DummyCrew );

	const CServiceCrew& GetCrew() { return m_Crew; }

private:
	CServiceCrew m_Crew;
};

#endif // __CRIRegistryCrewDlg__
