#ifndef __CRIRegistryCheckListTimeDlg__
#define __CRIRegistryCheckListTimeDlg__

/**
@file
Subclass of CheckListTimeDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryCheckListPagesGUIs.h"
#include "CRIRegistryOptions.h"

//// end generated include

/** Implementing CheckListTimeDlg */
class CRIRegistryCheckListTimeDlg : public CheckListTimeDlg
{
protected:
    // Handlers for CheckListTimeDlg events.
    void OnExitCtrl( wxFocusEvent& event );
    void OnOk( wxCommandEvent& event );
    void OnCancel( wxCommandEvent& event );

public:
    /** Constructor */
    CRIRegistryCheckListTimeDlg( wxWindow* parent, const wxString& turno = wxEmptyString, const wxString& inizio = wxEmptyString, const wxString& fine = wxEmptyString );

    wxString GetTurno() { return m_Turno->GetValue(); }
    wxString GetInizio() { return m_Inizio->GetValue(); }
    wxString GetFine() { return m_Fine->GetValue(); }
};

#endif // __CRIRegistryCheckListTimeDlg__
