#ifndef __CRIRegistryCheckListAddItemDlg__
#define __CRIRegistryCheckListAddItemDlg__

/**
@file
Subclass of CheckListAddItemDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryCheckListPagesGUIs.h"
#include "CRIRegistryCheckListTimeIntervalDlg.h"
#include "CRIRegistryAddFieldsDlg.h"

/** Implementing CheckListAddItemDlg */
class CRIRegistryCheckListAddItemDlg : public CheckListAddItemDlg
{
protected:
		// Handlers for CheckListAddItemDlg events.
		void OnEditPosition( wxCommandEvent& event );
		void OnExitCtrl( wxFocusEvent& event );
		void OnEditHours( wxCommandEvent& event );
		void OnOk( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );

public:
		/** Constructor */
		CRIRegistryCheckListAddItemDlg( wxWindow* parent );
};

#endif // __CRIRegistryCheckListAddItemDlg__
