#ifndef __CRIRegistrySelectDateRangeDlg__
#define __CRIRegistrySelectDateRangeDlg__

/**
@file
Subclass of SelectDateRangeDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"

/** Implementing SelectDateRangeDlg */
class CRIRegistrySelectDateRangeDlg : public SelectDateRangeDlg
{
protected:
	// Handlers for SelectDateRangeDlg events.
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	
public:
	/** Constructor */
	CRIRegistrySelectDateRangeDlg( wxWindow* parent, const wxString& text = wxEmptyString );
    const wxDateTime& GetDateStart(){ return m_dtDateStart; }
    const wxDateTime& GetDateEnd(){ return m_dtDateEnd; }

private:
    wxDateTime m_dtDateStart;
    wxDateTime m_dtDateEnd;
};

#endif // __CRIRegistrySelectDateRangeDlg__
