#ifndef __CRIRegistryMailingList__
#define __CRIRegistryMailingList__

/**
@file
Subclass of MailingList, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "db/dbSingleton.h"
#include "db/dbClass.h"
#include "MyFunctions.h"
#include "UsersManager.h"
#include "CRIRegistryMailAddressDlg.h"

/** Implementing MailingList */
class CRIRegistryMailingListDlg : public MailingListDlg
{
protected:
    // Handlers for MailingList events.
    void OnAdd( wxCommandEvent& event );
    void OnModify( wxCommandEvent& event );
    void OnDel( wxCommandEvent& event );
    void OnOk( wxCommandEvent& event );

public:
    /** Constructor */
    CRIRegistryMailingListDlg( wxWindow* parent );
    ~CRIRegistryMailingListDlg();

private:
	std::vector<dbClass>	m_Fields;
	std::vector<dbClass>::iterator GetFieldSelected();
    long GetItemSelected();
    void UpdateList();
};

#endif // __CRIRegistryMailingList__
