#ifndef __CRIRegistryOptionsDlg__
#define __CRIRegistryOptionsDlg__

/**
@file
Subclass of Options, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "CRIRegistryOptions.h"
#include "db\dbSingleton.h"
#include "CRIRegistryConstant.h"

/** Implementing Options */
class CRIRegistryOptionsDlg : public OptionsDlg
{
protected:
	// Handlers for Options events.
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );

public:
	/** Constructor */
	CRIRegistryOptionsDlg( wxWindow* parent );	
};

#endif // __CRIRegistryOptionsDlg__
