#ifndef __CRIRegistryServiceDlg__
#define __CRIRegistryServiceDlg__

/**
@file
Subclass of ServiceRegistryDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "dbClass/CService.h"
#include "CRIRegistryCrewDlg.h"
#include "CRIRegistryPatientDlg.h"
#include "UsersManager.h"

/** Implementing ServiceRegistryDlg */
class CRIRegistryServiceDlg : public ServiceRegistryDlg
{
protected:
	// Handlers for ServiceRegistryDlg events.
	void OnExitCtrl( wxFocusEvent& event );
	void OnCheck( wxCommandEvent& event );
	void OnCheckClose( wxCommandEvent& event );
	void OnPatientSelected( wxListEvent& event );
	void OnModifyCrew( wxCommandEvent& event );
	void OnAddCrew( wxCommandEvent& event );
	void OnDelCrew( wxCommandEvent& event );
	void OnModifyPatient( wxCommandEvent& event );
	void OnAddPatient( wxCommandEvent& event );
	void OnDelPatient( wxCommandEvent& event );
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );

public:
	/** Constructor */
	CRIRegistryServiceDlg( wxWindow* parent, const CService& service );

	const CService& GetService() { return m_Service; }
	
private:
	CService		m_Service;
	wxArrayString	m_aszServiceType;
	wxArrayString	m_asz118ServiceType;
	wxArrayString	m_aszInternalServiceType;
	wxArrayString	m_aszPaymentType;

	bool			m_bUserIsTheOwner;
	bool			m_bUserCanAdd;
	bool			m_bUserCanChangeAll;

	void UpdateCtrl();
	void UpdatePatientsCtrl();
	void UpdatePatientsListCtrl();
	void UpdateCrewsListCtrl();
	void UpdateRequestedCtrl();
	void UpdateData();
	long GetPatientItemSelected();
	long GetCrewItemSelected();
	std::vector<CServiceCrew>::iterator GetCrewSelected();
	std::vector<CServicePatient>::iterator GetPatientSelected();
	void SetPatientSelected( long i );
	bool CanBeClosed();
	void UpdateCtrlStatusByUser();
};

#endif // __CRIRegistryServiceDlg__
