#ifndef __CRIRegistryCAPDlg__
#define __CRIRegistryCAPDlg__

/**
@file
Subclass of CAPDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "MyFunctions.h"

/** Implementing CAPDlg */
class CRIRegistryCAPDlg : public CAPDlg
{
protected:
	// Handlers for CAPDlg events.
	void OnExitCtrl( wxFocusEvent& event );
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );

public:
	/** Constructor */
	CRIRegistryCAPDlg( wxWindow* parent, const wxString& cap = wxEmptyString, const wxString& comune = wxEmptyString, const wxString& provincia = wxEmptyString );

    wxString GetCap() { return m_Cap; }
    wxString GetComune() { return m_Comune; }
    wxString GetProvincia() { return m_Provincia; }

private:
    wxString m_Cap;
    wxString m_Comune;
    wxString m_Provincia;
};

#endif // __CRIRegistryCAPDlg__
