#ifndef __UsersManagerSetUsersPwdDlg__
#define __UsersManagerSetUsersPwdDlg__

/**
@file
Subclass of SetUsersPwdDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "UsersManager.h"
#include "MyFunctions.h"

/** Implementing SetUsersPwdDlg */
class UsersManagerSetUsersPwdDlg : public SetUsersPwdDlg
{
protected:
	// Handlers for SetUsersPwdDlg events.
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );

public:
	/** Constructor */
	UsersManagerSetUsersPwdDlg( wxWindow* parent );
	wxString GetNewPassword(){ return m_szPwd; }
	
private:
	wxString m_szPwd;
};

#endif // __UsersManagerSetUsersPwdDlg__
