#ifndef __UsersManagerDlg__
#define __UsersManagerDlg__

/**
@file
Subclass of UsersDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "UsersManager.h"

/** Implementing UsersDlg */
class UsersManagerDlg : public UsersDlg
{
protected:
	// Handlers for UsersDlg events.
	void OnConfirm( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	void OnExitCtrl( wxFocusEvent& event );
	void OnSelect( wxCommandEvent& event );
	void OnModify( wxCommandEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnDel( wxCommandEvent& event );
	void OnOk( wxCommandEvent& event );

public:
	/** Constructor */
	UsersManagerDlg( wxWindow* parent );
    ~UsersManagerDlg();

private:
	void EnableCtrl( bool enable );
	void ClearData();
	void UpdateUsersList();
	bool UpdateUserData();

	CUser m_CurrentUser;
	bool m_bUserAdded;
	bool m_bWaitConfirm;
	wxString m_DummyPwd;
};

#endif // __UsersManagerDlg__
