#ifndef __UsersManagerLogInDlg__
#define __UsersManagerLogInDlg__

/**
@file
Subclass of LogInDlg, which is generated by wxFormBuilder.
*/

#include "CRIRegistryGUIs.h"
#include "MyFunctions.h"

//// end generated include

/** Implementing LogInDlg */
class UsersManagerLogInDlg : public LogInDlg
{
protected:
	// Handlers for LogInDlg events.
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );

public:
	/** Constructor */
	UsersManagerLogInDlg( wxWindow* parent, const wxString& user );
	wxString GetUser() { return m_szUser; }
	wxString GetPassword(){ return m_szPwd; }
	
private:
	wxString m_szUser;
	wxString m_szPwd;
};

#endif // __UsersManagerLogInDlg__
