#ifndef __WizardPagesLuogoIntervento__
#define __WizardPagesLuogoIntervento__

/**
@file
Subclass of LuogoIntervento, which is generated by wxFormBuilder.
*/

#include "../CRIRegistryWizardPagesGUIs.h"
#include "../CRIRegistryCAPListDlg.h"
#include "../dbClass/CService.h"
#include "WizardPagesPazientiTrasportati.h"
#include "WizardPagesUtilizzoMezzo.h"
#include "WizardPagesLuogoTrasportato.h"

/** Implementing LuogoIntervento */
class WizardPagesLuogoIntervento : public LuogoIntervento
{
protected:
	// Handlers for LuogoIntervento events.
	void OnCheck( wxCommandEvent& event );
	void OnExitCtrl( wxFocusEvent& event );
    void OnKeyUp( wxKeyEvent& event );

public:
	/** Constructor */
	WizardPagesLuogoIntervento( wxWindow* parent, CService* service );	
	~WizardPagesLuogoIntervento(){ }
	
protected:
	virtual void OnEnter();
	virtual void OnExit();
	virtual bool GoNext();
	virtual bool GoPrev();

private:
	CService*					    m_pService;
    WizardPagesPazientiTrasportati* m_pPage1;
    WizardPagesLuogoTrasportato*    m_pPage2;
};

#endif // __WizardPagesLuogoIntervento__
