#ifndef __WizardPagesFine__
#define __WizardPagesFine__

/**
@file
Subclass of Fine, which is generated by wxFormBuilder.
*/

#include "../CRIRegistryWizardPagesGUIs.h"
#include "../dbClass/CService.h"

/** Implementing Fine */
class WizardPagesFine : public Fine
{
public:
	/** Constructor */
	WizardPagesFine( wxWindow* parent, CService* service  );
	~WizardPagesFine() { }
	
protected:
	virtual void OnEnter();
	virtual void OnExit();
	virtual bool GoNext();
	virtual bool GoPrev();

private:
	CService*	m_pService;
};

#endif // __WizardPagesFine__
