#ifndef __WizardPagesLuogoIntervento118__
#define __WizardPagesLuogoIntervento118__

/**
@file
Subclass of LuogoIntervento118, which is generated by wxFormBuilder.
*/

#include "../CRIRegistryWizardPagesGUIs.h"
#include "../CRIRegistryCAPListDlg.h"
#include "../dbClass/CService.h"
#include "WizardPagesInfoServizio118.h"

/** Implementing LuogoIntervento118 */
class WizardPagesLuogoIntervento118 : public LuogoIntervento118
{
protected:
	// Handlers for LuogoIntervento118 events.
	void OnCheck( wxCommandEvent& event );
	void OnExitCtrl( wxFocusEvent& event );
    void OnKeyUp( wxKeyEvent& event );

public:
	/** Constructor */
	WizardPagesLuogoIntervento118( wxWindow* parent, CService* service );
    ~WizardPagesLuogoIntervento118(){ }

protected:
	virtual void OnEnter();
	virtual void OnExit();
	virtual bool GoNext();
	virtual bool GoPrev();

private:
	CService*					    m_pService;
    WizardPagesInfoServizio118*     m_pPage1;
};

#endif // __WizardPagesLuogoIntervento118__
