#ifndef __WizardPagesPazientiTrasportati118__
#define __WizardPagesPazientiTrasportati118__

/**
@file
Subclass of PazientiTrasportati, which is generated by 
wxFormBuilder. 
*/

#include "../CRIRegistryWizardPagesGUIs.h"
#include "../CRIRegistryAddPatient118Dlg.h"
#include "../dbClass/CService.h"
#include "WizardPagesUtilizzoMezzo.h"

/** Implementing PazientiTrasportati */
class WizardPagesPazientiTrasportati118 : public PazientiTrasportati
{
protected:
	// Handlers for PazientiTrasportati events.
    void OnAdd( wxCommandEvent& event );
    void OnModify( wxCommandEvent& event );
    void OnDel( wxCommandEvent& event );
    void OnSize( wxSizeEvent& event );

public:
	/** Constructor */
	WizardPagesPazientiTrasportati118( wxWindow* parent, CService* service );	
	~WizardPagesPazientiTrasportati118(){ }
	
protected:
	virtual void OnEnter();
	virtual void OnExit();
	virtual bool GoNext();
	virtual bool GoPrev();

private:
	CService*			            m_pService;
	WizardPagesUtilizzoMezzo*		m_pPage;
    void UpdatePatientsListCtrl();
    long GetPatientItemSelected();
    std::vector<CServicePatient>::iterator GetPatientSelected();
};

#endif // __WizardPagesPaziente__
