#ifndef __WizardPagesEquipaggio__
#define __WizardPagesEquipaggio__

/**
@file
Subclass of Equipaggio, which is generated by wxFormBuilder.
*/

#include "../CRIRegistryWizardPagesGUIs.h"
#include "../CRIRegistryCrewDlg.h"
#include "../dbClass/CService.h"
#include "WizardPagesRichiesto.h"

/** Implementing Equipaggio */
class WizardPagesEquipaggio : public Equipaggio
{
protected:
	// Handlers for Equipaggio events.
    void OnChoice( wxCommandEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnModify( wxCommandEvent& event );
	void OnDel( wxCommandEvent& event );
	void OnSize( wxSizeEvent& event );

public:
	/** Constructor */
	WizardPagesEquipaggio( wxWizard* parent, CService* service );
	~WizardPagesEquipaggio(){ }

protected:
	virtual void OnEnter();
	virtual void OnExit();
	virtual bool GoNext();
	virtual bool GoPrev();

private:
	CService*				m_pService;
	WizardPagesRichiesto*	m_pPage;
    CFleet                  m_Ambulance;
	void SelectCrew();
	void UpdateCrewsListCtrl();
	long GetCrewItemSelected();
	std::vector<CServiceCrew>::iterator GetCrewSelected();
};

#endif // __WizardPagesEquipaggio__
