#ifndef __WizardPagesGruppo__
#define __WizardPagesGruppo__

/**
@file
Subclass of Gruppo, which is generated by wxFormBuilder.
*/

#include "../CRIRegistryWizardPagesGUIs.h"
#include "../dbClass/CService.h"
#include "WizardPagesData.h"

/** Implementing Gruppo */
class WizardPagesGruppo : public Gruppo
{
public:
	/** Constructor */
	WizardPagesGruppo( wxWizard* parent, CService* service );
	~WizardPagesGruppo(){ }

protected:
	virtual void OnEnter();
	virtual void OnExit();
	virtual bool GoNext();
	virtual bool GoPrev();

private:
	CService*		    m_pService;
	WizardPagesData*	m_pPage;
};

#endif // __WizardPagesGruppo__
