#ifndef __WizardPagesRichiesto__
#define __WizardPagesRichiesto__

/**
@file
Subclass of Richiesto, which is generated by wxFormBuilder.
*/

#include "../CRIRegistryWizardPagesGUIs.h"
#include "../dbClass/CService.h"
#include "WizardPagesLuogoIntervento.h"
#include "WizardPagesLuogoIntervento118.h"
#include "WizardPagesPaziente.h"
#include "WizardPagesRichiedente.h"
#include "WizardPagesUtilizzoMezzo.h"

/** Implementing Richiesto */
class WizardPagesRichiesto : public Richiesto
{
public:
	/** Constructor */
	WizardPagesRichiesto( wxWizard* parent, CService* service );	
	~WizardPagesRichiesto(){ }

protected:
	void OnCheck( wxCommandEvent& event );
	void OnChoice( wxCommandEvent& event );
	void OnExitCtrl( wxFocusEvent& event );

protected:
	virtual void OnEnter();
	virtual void OnExit();
	virtual bool GoNext();
	virtual bool GoPrev();

private:
	CService*					    m_pService;
	wxString					    m_LastRequestedBy;
    WizardPagesLuogoIntervento118*	m_pPage0;
    WizardPagesLuogoIntervento*	    m_pPage1;
    WizardPagesPaziente*	        m_pPage2;
    WizardPagesRichiedente*	        m_pPage3;
	WizardPagesUtilizzoMezzo*	    m_pPage4;
	wxArrayString				    m_aszType118;
	wxArrayString				    m_aszTypeOrdinary;
	wxArrayString				    m_aszTypeInternal;
};

#endif // __WizardPagesRichiesto__
