#ifndef __WizardPagesPaziente__
#define __WizardPagesPaziente__

/**
@file
Subclass of Paziente, which is generated by wxFormBuilder.
*/

#include "../CRIRegistryWizardPagesGUIs.h"
#include "../dbClass/CService.h"
#include "WizardPagesLuogoIntervento.h"

/** Implementing Paziente */
class WizardPagesPaziente : public Paziente
{
protected:
	// Handlers for Paziente events.
	void OnExitCtrl( wxFocusEvent& event );

public:
	/** Constructor */
	WizardPagesPaziente( wxWindow* parent, CService* service );
    ~WizardPagesPaziente() { }	

protected:
	virtual void OnEnter();
	virtual void OnExit();
	virtual bool GoNext();
	virtual bool GoPrev();

private:
	CService*				    m_pService;
	WizardPagesLuogoIntervento*	m_pPage;
};

#endif // __WizardPagesPaziente__
