#ifndef __WizardPagesRichiedente__
#define __WizardPagesRichiedente__

/**
@file
Subclass of Richiedente, which is generated by wxFormBuilder.
*/

#include "../CRIRegistryWizardPagesGUIs.h"
#include "../dbClass/CService.h"
#include "WizardPagesLuogoIntervento.h"

/** Implementing Richiedente */
class WizardPagesRichiedente : public Richiedente
{
protected:
	// Handlers for Richiedente events.
	void OnExitCtrl( wxFocusEvent& event );

public:
	/** Constructor */
	WizardPagesRichiedente( wxWindow* parent, CService* service  );
	~WizardPagesRichiedente() { }

protected:
	virtual void OnEnter();
	virtual void OnExit();
	virtual bool GoNext();
	virtual bool GoPrev();

private:
	CService*				    m_pService;
    WizardPagesLuogoIntervento*	m_pPage;
};

#endif // __WizardPagesRichiedente__
