#ifndef __WizardPagesData__
#define __WizardPagesData__

/**
@file
Subclass of Data, which is generated by wxFormBuilder.
*/

#include "../CRIRegistryWizardPagesGUIs.h"
#include "../dbClass/CService.h"
#include "WizardPagesEquipaggio.h"

/** Implementing Data */
class WizardPagesData : public Data
{
protected:
	// Handlers for Orario events.
	void OnExitCtrl( wxFocusEvent& event );

public:
	/** Constructor */
	WizardPagesData( wxWizard* parent, CService* service );
	~WizardPagesData(){ }

protected:
	virtual void OnEnter();
	virtual void OnExit();
	virtual bool GoNext();
	virtual bool GoPrev();

private:
	CService*				m_pService;
	WizardPagesEquipaggio*	m_pPage;
};

#endif // __WizardPagesData__
